SELECT
    CAST(distributed_statement_id AS varchar(36)) AS normalized_operation_id,
    CAST('{{WAREHOUSE_ITEM_ID}}' AS varchar(36)) AS warehouse_item_id,
    CAST('{{WAREHOUSE_NAME}}' AS varchar(128)) AS warehouse_name,
    database_name,
    submit_time,
    start_time,
    end_time,
    statement_type,
    total_elapsed_time_ms,
    allocated_cpu_time_ms,
    login_name,
    row_count,
    status,
    session_id,
    connection_id,
    program_name,
    query_hash,
    label,
    result_cache_hit,
    sql_pool_name,
    error_code,
    error_severity,
    error_state,
    data_scanned_remote_storage_mb,
    data_scanned_memory_mb,
    data_scanned_disk_mb,
    LEFT(command, 4000) AS command
FROM queryinsights.exec_requests_history
WHERE start_time >= DATEADD(day, -30, SYSUTCDATETIME());
